spring.application.name=todo

# Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://dpg-d6on1pchg0os73etk2mg-a.oregon-postgres.render.com:5432/task_management_gfv8?sslmode=require}
spring.datasource.username=${DB_USERNAME:adrin}
spring.datasource.password=${DB_PASSWORD:B7jjHkK7KjsyU89TFAdCtp68R26xgqn0}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration (read from .env)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.config.import=optional:file:.env[.properties]

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.health.db.enabled=true
